2.1: 2.1-build 2.1-basic-test

2.2: 2.2-build
ifdef RUN_TESTS
	printf "this line is 26 chars long" | $(VALGRIND) ./bin/$@
	printf "" | $(VALGRIND) ./bin/$@
endif

2.3: 2.3-build 2.3-basic-test
2.4: 2.4-build 2.4-basic-test
2.5: 2.5-build 2.5-basic-test
2.6: 2.6-build 2.6-basic-test
2.7: 2.7-build 2.7-basic-test
2.8: 2.8-build 2.8-basic-test
2.9: 2.9-build 2.9-basic-test
2.10: 2.10-build 2.10-basic-test
